// Code generated by ogen, DO NOT EDIT.

package on

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetSample implements getSample operation.
//
// Sample.
//
// GET /
func (UnimplementedHandler) GetSample(ctx context.Context, params GetSampleParams) (r GetSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostSample implements postSample operation.
//
// Sample.
//
// POST /
func (UnimplementedHandler) PostSample(ctx context.Context, req *PostSampleReq) (r PostSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
