// Code generated by ogen, DO NOT EDIT.

package off

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetSample implements getSample operation.
//
// Sample.
//
// GET /
func (UnimplementedHandler) GetSample(ctx context.Context, params GetSampleParams) (r GetSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostSampl implements postSampl operation.
//
// Sample.
//
// POST /
func (UnimplementedHandler) PostSampl(ctx context.Context, req *PostSamplReq) (r PostSamplRes, _ error) {
	return r, ht.ErrNotImplemented
}
